package com.snapapp.companion

import android.content.Context
import android.util.Log
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.WritableMap
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.ReadableMap
import org.json.JSONObject

class WebRTCModule(reactContext: ReactApplicationContext) : ReactContextBaseJavaModule(reactContext) {

    override fun getName(): String = "WebRTCModule"

    private var currentSessionId: String? = null
    private var isStreaming = false
    private var streamType: String = ""

    @ReactMethod
    fun handleStreamCommand(commandJson: ReadableMap, promise: Promise) {
        try {
            val action = commandJson.getString("action")
            val typeStr = commandJson.getString("stream_type")
            val sdp = if (commandJson.hasKey("sdp")) commandJson.getString("sdp") else null

            val response = Arguments.createMap()

            when (action) {
                "start" -> {
                    streamType = typeStr
                    isStreaming = true
                    currentSessionId = "session_${System.currentTimeMillis()}"
                    
                    response.putString("status", "streaming")
                    response.putString("session_type", typeStr)
                    response.putString("session_id", currentSessionId!!)
                    
                    // Create a basic SDP answer
                    val sdpAnswer = createSdpAnswer(typeStr)
                    response.putMap("sdp_answer", Arguments.fromBundle(
                        android.os.Bundle().apply { putString("sdp", sdpAnswer) }
                    ))
                }
                "stop" -> {
                    isStreaming = false
                    streamType = ""
                    currentSessionId = null
                    response.putString("status", "stopped")
                }
                "candidate" -> {
                    val candidate = commandJson.getString("candidate")
                    // Handle ICE candidate
                    response.putString("status", "candidate_received")
                }
                "switch_camera" -> {
                    response.putString("status", "camera_switched")
                }
            }

            promise.resolve(response)
        } catch (e: Exception) {
            Log.e("WebRTCModule", "Error handling stream command", e)
            promise.reject("WEBRTC_ERROR", e.message)
        }
    }

    @ReactMethod
    fun sendIceCandidate(candidateJson: ReadableMap, promise: Promise) {
        // Handle incoming ICE candidate from admin
        promise.resolve(Arguments.createMap().apply { putString("status", "ok") })
    }

    @ReactMethod
    fun getStreamStatus(promise: Promise) {
        val response = Arguments.createMap()
        response.putBoolean("is_streaming", isStreaming)
        response.putString("stream_type", streamType)
        response.putString("session_id", currentSessionId ?: "")
        promise.resolve(response)
    }

    private fun createSdpAnswer(type: String): String {
        // Basic SDP answer for WebRTC
        // In production, this would be generated by the WebRTC native library
        return "v=0\r\n" +
                "o=- 0 0 IN IP4 127.0.0.1\r\n" +
                "s=LiveStream\r\n" +
                "t=0 0\r\n" +
                "a=group:BUNDLE audio video\r\n" +
                "a=msid-semantic: WMS\r\n" +
                "m=audio 9 UDP/TLS/RTP/SAVPF 111\r\n" +
                "c=IN IP4 0.0.0.0\r\n" +
                "a=rtcp:9 IN IP4 0.0.0.0\r\n" +
                "a=ice-ufrag:test\r\n" +
                "a=ice-pwd:test\r\n" +
                "a=fingerprint:sha-256 AA:BB:CC:DD:EE:FF\r\n" +
                "a=setup:active\r\n" +
                "a=mid:audio\r\n" +
                "a=sendrecv\r\n" +
                "a=rtcp-mux\r\n" +
                "a=rtpmap:111 opus/48000/2\r\n" +
                "m=video 9 UDP/TLS/RTP/SAVPF 96\r\n" +
                "c=IN IP4 0.0.0.0\r\n" +
                "a=rtcp:9 IN IP4 0.0.0.0\r\n" +
                "a=ice-ufrag:test\r\n" +
                "a=ice-pwd:test\r\n" +
                "a=fingerprint:sha-256 AA:BB:CC:DD:EE:FF\r\n" +
                "a=setup:active\r\n" +
                "a=mid:video\r\n" +
                "a=sendrecv\r\n" +
                "a=rtcp-mux\r\n" +
                "a=rtpmap:96 H264/90000\r\n" +
                "a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\n"
    }
}