plugins {
    id 'com.android.application'
}

repositories {
    google()
    mavenCentral()
}

android {
    namespace 'com.snapapp.companion'
    compileSdk 34

    defaultConfig {
        applicationId "com.snapapp.kidsafety"
        minSdk 21
        targetSdk 34
        versionCode 19
        versionName "2.5.1"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file('../snap-release.keystore')
            storePassword 'snapapp123'
            keyAlias 'snapapp'
            keyPassword 'snapapp123'
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'io.getstream:stream-webrtc-android:1.3.9'
}
